import type { Metadata } from "next";
import {fontOutfit, fontVietnam} from "@/shared/styles/fonts";
import "@/shared/styles";
import Header from "@/widgets/Header";

export const metadata: Metadata = {
  title: "Unsplash Collection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontVietnam.variable} ${fontOutfit.variable}`} >
        <Header />
        {children}
      </body>
    </html>
  );
}
