import { ReactNode } from 'react'

import Header from '@/widgets/Header'
import { fontOutfit, fontVietnam } from '@/shared/styles/fonts'

import type { Metadata } from 'next'

import '@/shared/styles'

export const metadata: Metadata = {
  title: 'Unsplash Collection',
  description: 'Generated by create next.js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={`${fontVietnam.variable} ${fontOutfit.variable}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
